theme: jekyll-theme-slate
title: Predicting Subway Usage in the Covid-19 Era
description: Turnstile data taken from Metropolitan Transportation Authority for the purposes of exploratory analysis and forecasting.
